---
title: "diabetes_modeling_korea"
format: html
editor: visual
output-file: html
---

### Libraries

```{r}
library(tidyverse)
library(readxl)
library(rriskDistributions)
library(writexl)
```

## Importing data

```{r}
# loading danish inputs, sex, LOD, BPS percentiles & diabetes incidence
# doing lognormal distribution to the danish percentiles
df <- read_excel("/Users/idasofieadrian/Desktop/DTU/SPECIALE/Speciale/data/diabetes korea (GBD).xlsx") %>%
  mutate(
    meanlog_dk = log(p_50),
    sdlog_dk   = (log(p_75) - log(p_25)) / (qnorm(0.75) - qnorm(0.25)),
    # exepected fraction of population above LOD
    p_detectable_dk = 1 - plnorm(LOD, meanlog_dk, sdlog_dk),
    # arithemtic mean
    # is this right?
    mean_exp_dk = exp(meanlog_dk + 0.5 * sdlog_dk^2), # not in use
    median_dk = p_50 # in use, data is right skewed, see the bottom
  )
```

## Korean study inputs, BPS and diabetes

```{r}
# Supplementary Table S6: DM ORs among participants with BPS > LOD
OR_t2  <- 1.73
LCL_t2 <- 1.00
UCL_t2 <- 2.98

OR_t3  <- 2.13
LCL_t3 <- 1.29
UCL_t3 <- 3.50

# Convert 95% CI to log-scale SE
# simulating uncertainty
se_t2 <- (log(UCL_t2) - log(LCL_t2)) / (2 * 1.96)
se_t3 <- (log(UCL_t3) - log(LCL_t3)) / (2 * 1.96)

```

```{r}
# Supplementary Table S1: Korean detectable BPS distribution (> LOD)
# Using p25, p50, and p75 to fit a lognormal distribution

fit_kor <- get.lnorm.par(
  p = c(0.25, 0.50, 0.75),
  q = c(0.029, 0.049, 0.104),
  show.output = FALSE,
  plot = TRUE
)

# extract the fitted lognormal parameters as ordinary numbers
meanlog_kor <- unname(fit_kor["meanlog"])
sdlog_kor   <- unname(fit_kor["sdlog"])

# Simulate Korean detectable exposure distribution
# If detectable Korean BPS is lognormal, what concentrations are typical in tertiles 1, 2, and 3?
set.seed(123)
x_kor <- rlnorm(1e6, meanlog = meanlog_kor, sdlog = sdlog_kor)

# Tertile cutpoints among detectable Korean values
cut1 <- qlnorm(1/3, meanlog = meanlog_kor, sdlog = sdlog_kor)
cut2 <- qlnorm(2/3, meanlog = meanlog_kor, sdlog = sdlog_kor)

# Medians within each tertile
# finding the typical dose within the tertile
# cuts represent the boundaries between the tertiles
# dose_t1 <- median(x_kor[x_kor <= cut1])
# dose_t2 <- median(x_kor[x_kor > cut1 & x_kor <= cut2])
# dose_t3 <- median(x_kor[x_kor > cut2])

# trying with mean
dose_t1 <- mean(x_kor[x_kor <= cut1])
dose_t2 <- mean(x_kor[x_kor > cut1 & x_kor <= cut2])
dose_t3 <- mean(x_kor[x_kor > cut2])

# which value should I use to cap?
# dose_t3_med <- median(x_kor[x_kor > cut2])

df <- df %>%
  mutate(med_cap = dose_t3)


## Build dose-response dataset and fit linear trend ##
# dose = representative exposures (medians) for the 3 tertiles
# dose_c = making tertile 1 the reference point/baseline where log(RR)=0, RR=1
# IS dose_c NECESSARY?
# logrr = converting the RR to the log scale
# se = using the SE for the log-risk estimates
study_dat <- tibble(
  dose   = c(dose_t1, dose_t2, dose_t3),
  dose_c = c(dose_t1, dose_t2, dose_t3) - dose_t1,
  logrr  = log(c(1, OR_t2, OR_t3)),
  se     = c(NA, se_t2, se_t3)
)

# CI bounds from SE for plotting
study_dat <- study_dat %>%
  mutate(
    logrr_lower = logrr - 1.96 * se,
    logrr_upper = logrr + 1.96 * se
  )


# fitting linear model, trying to finde the slope beta of the best straight line
# lm(logrr ~ 0 + dose_c) fits the line without an intercept to force it through (0,0) 
# this means dose_c = 0, logrr = 0 which makes 1 at reference dose (RR = e^logrr = 1, where logrr = 0)
# data = study_dat[2:3, ], uses just tertile 2 and 3 (removes the first row) because tertile 1 is reference

fit_lin <- lm(logrr ~ 0 + dose_c,
              data = study_dat[2:3, ],
              weights = 1 / study_dat$se[2:3]^2) # smaller SE -> larger weight -> more influence

### SPLINE ###
study_dat2 <- study_dat %>%
  mutate(w = c(1e6, 1/se_t2^2, 1/se_t3^2))

fit_quad <- lm(logrr ~ 0 + dose_c + I(dose_c^2),
               data = study_dat2,
               weights = w)

# estimated slope of line + uncertainty of the estimated slope
beta_hat <- unname(coef(fit_lin)["dose_c"])
beta_se  <- summary(fit_lin)$coefficients["dose_c", "Std. Error"]

# reference dose
x_ref <- dose_t1


beta_hat
beta_se
summary(fit_lin)
study_dat

```

```{r}
# making a sequence of dose values for plotting
# now also adding Model uncertainty 
pred_grid <- tibble(
  dose = seq(min(study_dat$dose), max(df$med_cap), length.out = 100)
) %>%
  mutate(dose_c = dose - dose_t1) %>%
  bind_cols(
    predict(fit_lin, newdata = ., interval = "confidence", level = 0.95) %>%
      as_tibble() %>%
      rename(logrr_fit = fit, logrr_lwr = lwr, logrr_upr = upr)
  )


# plot
p_logrr <- ggplot() +
  geom_line(
    data = pred_grid,
    aes(x = dose, y = logrr_fit),
    color = "#045A8DFF",
    linewidth = 1
  ) +
  geom_point(
    data = study_dat,
    aes(x = dose, y = logrr),
    color = "#045A8DFF",
    size = 3
  ) +
  labs(
    title = "BPS and diabetes risk",
    x = "Urinary BPS concentration",
    y = "log(OR)"
  ) +
  theme_classic() +
  theme(plot.title = element_text(size = 16, face = "bold"))

p_logrr

# underestimation of t2?
# overestimating t3?


# saving plot
ggsave(
  filename = "logrr_linear_model_korea.png",
  plot = p_logrr,
  width = 7,
  height = 5,
  dpi = 300
)
```

## New plot

```{r}
p_logrr_new <- ggplot() +
  geom_ribbon(
    data = pred_grid,
    aes(x = dose, ymin = logrr_lwr, ymax = logrr_upr),
    fill = "#045A8DFF",
    alpha = 0.12
  ) +
  geom_line(
    data = pred_grid,
    aes(x = dose, y = logrr_fit),
    color = "#045A8DFF",
    linewidth = 1
  ) +
  geom_errorbar(
    data = study_dat,
    aes(x = dose, ymin = logrr_lower, ymax = logrr_upper),
    color = "#045A8DFF",
    width = 0.006,
    linewidth = 0.6
  ) +
  geom_point(
    data = study_dat,
    aes(x = dose, y = logrr),
    color = "#045A8DFF",
    size = 3.2
  ) +
  geom_segment(
  aes(
    x = min(study_dat$dose),
    xend = max(df$med_cap),
    y = 0,
    yend = 0
  ),
  linetype = "dashed",
  linewidth = 0.4,
  color = "grey40"
  ) +
  geom_vline(
  xintercept = unique(df$med_cap),
  linetype = "dashed",
  linewidth = 0.4,
  color = "grey40"
  ) +
  labs(
    title = "Linear dose-response model for BPS and T2D risk",
    x = "Urinary BPS concentration",
    y = "log(OR)"
  ) +
  theme_classic(base_size = 14) +
  theme(
    plot.title = element_text(size = 18, face = "bold"),
    axis.title = element_text(size = 15),
    axis.text = element_text(size = 13)
  )

p_logrr_new

# saving plot
ggsave(
  filename = "NEW_logrr_linear_model_korea.png",
  plot = p_logrr_new,
  width = 7,
  height = 5,
  dpi = 300
)
```

## Duration inputs for YLD

```{r}
# Median age at onset of type 2 diabetes in DK
age_m <- 62.1
age_f <- 64.6

# Life expectancy in DK in 2023
life_m <- 79.9
life_f <- 83.7

# estimating the duration
D_m <- life_m - age_m
D_f <- life_f - age_f

# adding to dataframe
df <- df %>%
  mutate(
    D_years = case_when(
      str_detect(group, "^Male")   ~ D_m,
      str_detect(group, "^Female") ~ D_f,
      TRUE ~ NA_real_
    )
  )
```

## Inputs for YLL

```{r}
# deaths and diabetes from GBD (DK + T2D) (2023)
deaths_f <- 599.79
deaths_m <- 783.06

yll_f <- 7896.75
yll_m <- 12928.04

# calculating standard expected years of life lost
seyll_f <- yll_f / deaths_f
seyll_m <- yll_m / deaths_m

# adding to dataframe
df <- df %>%
  mutate(
    deaths = case_when(
      str_detect(group, "^Female") ~ deaths_f,
      str_detect(group, "^Male")   ~ deaths_m,
      TRUE ~ NA_real_
    ),
    seyll = case_when(
      str_detect(group, "^Female") ~ seyll_f,
      str_detect(group, "^Male")   ~ seyll_m,
      TRUE ~ NA_real_
    )
  )
```

## Disability weight inputs

```{r}
# Uncomplicated diabetes mellitus type 2
# DW_mode <- 0.049011415
# DW_min  <- 0.0311213425
# DW_max  <- 0.072092547

# downloaded from GBD
# Sex-specific YLD estimates downloaded from GBD
YLD_fem       <- 8355.60842682979
YLD_fem_lower <- 5617.300593266269
YLD_fem_upper <- 11465.14910195645

YLD_male       <- 13225.904475796962
YLD_male_lower <- 8916.644865520693
YLD_male_upper <- 17957.837169143662


# Combined YLD estimates used to derive the average disability weight
YLD_total       <- YLD_male + YLD_fem
YLD_lower_total <- YLD_male_lower + YLD_fem_lower
YLD_upper_total <- YLD_male_upper + YLD_fem_upper


# Combined prevalence estimates downloaded from GBD
prev_total <- 194510.88289338743 + 122399.73795153094

prev_lower_total <- 169049.8026957066 +
  111088.08159363415

prev_upper_total <- 211790.44277738212 +
  134597.21198640313


# Average effective disability-weight estimates
DW_mode <- YLD_total / prev_total
DW_min  <- YLD_lower_total / prev_upper_total
DW_max  <- YLD_upper_total / prev_lower_total

DW_mode
DW_min
DW_max


# Add sex-specific central and uncertainty estimates to dataframe
df <- df %>%
  mutate(
    YLD_mode = case_when(
      str_detect(group, "^Female") ~ YLD_fem,
      str_detect(group, "^Male")   ~ YLD_male,
      TRUE ~ NA_real_
    ),
    YLD_lower = case_when(
      str_detect(group, "^Female") ~ YLD_fem_lower,
      str_detect(group, "^Male")   ~ YLD_male_lower,
      TRUE ~ NA_real_
    ),
    YLD_upper = case_when(
      str_detect(group, "^Female") ~ YLD_fem_upper,
      str_detect(group, "^Male")   ~ YLD_male_upper,
      TRUE ~ NA_real_
    )
  )
```

## Helper functions

```{r}
# PERT distribution for disability weight uncertainty
rpert <- function(n, min, mode, max) {
  alpha <- 1 + 4 * (mode - min) / (max - min)
  beta  <- 1 + 4 * (max - mode) / (max - min)
  min + rbeta(n, alpha, beta) * (max - min)
}

```

## Monte Carlo

```{r}
run_mc_row_daly_korea_simple <- function(
  i_diabetes, med_cap, p_detectable_dk,
  D_years, deaths, seyll,
  YLD_mode,
  YLD_lower,
  YLD_upper,
  DW_min, DW_mode, DW_max,
  beta_hat, beta_se, x_ref
) {

  # uncertainty in slope
  # draw one possible value of the dose-response slope from a normal distribution centered at the estimated slope
  beta <- rnorm(1, mean = beta_hat, sd = beta_se)

  # RR at average detectable Danish exposure
  # log(RR) = beta * (Danish exposure - Korean reference dose)
  rr_median <- exp(beta * (med_cap - x_ref))

  # PAF for only detectable population
  PAF <- (p_detectable_dk * (rr_median - 1)) /
    (1 + p_detectable_dk * (rr_median - 1))

  # Attributable cases using incidence directly
  AC <- PAF * i_diabetes

  # draw a disability weight
  DW <- rpert(1, DW_min, DW_mode, DW_max)

  # incidence-based attributable YLD
  YLD_incidence <- AC * D_years * DW

  # prevalence/GBD-based attributable YLD
  YLD_total_draw <- rpert(
    1,
    min  = YLD_lower,
    mode = YLD_mode,
    max  = YLD_upper
  )
  
  YLD_prevalence <- PAF * YLD_total_draw

  # attributable deaths
  AD <- PAF * deaths

  # years of life lost
  YLL <- AD * seyll

  # DALYs using incidence-based and prevalence-based YLD
  DALY_incidence <- YLD_incidence + YLL
  DALY_prevalence <- YLD_prevalence + YLL

  tibble(
    PAF = PAF,
    AC = AC,
    AD = AD,
    YLD_incidence = YLD_incidence,
    YLD_prevalence = YLD_prevalence,
    YLL = YLL,
    DALY_incidence = DALY_incidence,
    DALY_prevalence = DALY_prevalence
  )
}
```

```{r}
run_mc_summary_daly_korea_simple <- function(
  i_diabetes, med_cap, p_detectable_dk,
  D_years, deaths, seyll,
  YLD_mode,
  YLD_lower,
  YLD_upper,
  DW_min, DW_mode, DW_max,
  beta_hat, beta_se, x_ref,
  nsim_outer = 1000
) {

  sims <- map_dfr(seq_len(nsim_outer), ~
    run_mc_row_daly_korea_simple(
      i_diabetes = i_diabetes,
      med_cap = med_cap,
      p_detectable_dk = p_detectable_dk,
      D_years = D_years,
      deaths = deaths,
      seyll = seyll,
      YLD_mode = YLD_mode,
      YLD_lower = YLD_lower,
      YLD_upper = YLD_upper,
      DW_min = DW_min,
      DW_mode = DW_mode,
      DW_max = DW_max,
      beta_hat = beta_hat,
      beta_se = beta_se,
      x_ref = x_ref
    )
  )

  tibble(
    PAF_med  = median(sims$PAF, na.rm = TRUE),
    PAF_lo   = quantile(sims$PAF, 0.025, na.rm = TRUE),
    PAF_hi   = quantile(sims$PAF, 0.975, na.rm = TRUE),

    AC_med   = median(sims$AC, na.rm = TRUE),
    AC_lo    = quantile(sims$AC, 0.025, na.rm = TRUE),
    AC_hi    = quantile(sims$AC, 0.975, na.rm = TRUE),

    AD_med   = median(sims$AD, na.rm = TRUE),
    AD_lo    = quantile(sims$AD, 0.025, na.rm = TRUE),
    AD_hi    = quantile(sims$AD, 0.975, na.rm = TRUE),

    YLD_incidence_med = median(sims$YLD_incidence, na.rm = TRUE),
    YLD_incidence_lo  = quantile(sims$YLD_incidence, 0.025, na.rm = TRUE),
    YLD_incidence_hi  = quantile(sims$YLD_incidence, 0.975, na.rm = TRUE),

    YLD_prevalence_med = median(sims$YLD_prevalence, na.rm = TRUE),
    YLD_prevalence_lo  = quantile(sims$YLD_prevalence, 0.025, na.rm = TRUE),
    YLD_prevalence_hi  = quantile(sims$YLD_prevalence, 0.975, na.rm = TRUE),

    YLL_med  = median(sims$YLL, na.rm = TRUE),
    YLL_lo   = quantile(sims$YLL, 0.025, na.rm = TRUE),
    YLL_hi   = quantile(sims$YLL, 0.975, na.rm = TRUE),

    DALY_incidence_med = median(sims$DALY_incidence, na.rm = TRUE),
    DALY_incidence_lo  = quantile(sims$DALY_incidence, 0.025, na.rm = TRUE),
    DALY_incidence_hi  = quantile(sims$DALY_incidence, 0.975, na.rm = TRUE),

    DALY_prevalence_med = median(sims$DALY_prevalence, na.rm = TRUE),
    DALY_prevalence_lo  = quantile(sims$DALY_prevalence, 0.025, na.rm = TRUE),
    DALY_prevalence_hi  = quantile(sims$DALY_prevalence, 0.975, na.rm = TRUE)
  )
}
```

```{r}
results_daly_korea_simple <- df %>%
  mutate(
    mc = pmap(
      list(
        i_diabetes,
        med_cap,
        p_detectable_dk,
        D_years,
        deaths,
        seyll,
        YLD_mode,
        YLD_lower,
        YLD_upper
      ),
      ~ run_mc_summary_daly_korea_simple(
        i_diabetes = ..1,
        med_cap = ..2,
        p_detectable_dk = ..3,
        D_years = ..4,
        deaths = ..5,
        seyll = ..6,
        YLD_mode  = ..7,
        YLD_lower = ..8,
        YLD_upper = ..9,
        DW_min = DW_min,
        DW_mode = DW_mode,
        DW_max = DW_max,
        beta_hat = beta_hat,
        beta_se = beta_se,
        x_ref = x_ref,
        nsim_outer = 1000
      )
    )
  ) %>%
  unnest(mc)

results_daly_korea_simple
```

```{r}
getwd()
write_xlsx(results_daly_korea_simple, "/Users/idasofieadrian/Desktop/DTU/SPECIALE/Speciale/results/results_diabetes_korea_simple_CAPPED.xlsx")
```

## Checking percentiles

```{r}
# Original Korean target percentiles
target_kor <- tibble(
  percentile = c("p25", "p50", "p75"),
  target = c(0.029, 0.049, 0.104)
)

# Back-calculated percentiles from fitted lognormal
check_kor <- tibble(
  percentile = c("p25", "p50", "p75"),
  fitted = qlnorm(c(0.25, 0.50, 0.75), meanlog_kor, sdlog_kor)
)

# Compare
compare_kor <- target_kor %>%
  left_join(check_kor, by = "percentile") %>%
  mutate(
    abs_diff = fitted - target,
    rel_diff_pct = 100 * (fitted - target) / target
  )

compare_kor

# qlnorm() gives you the quantile of a lognormal distribution

# target = the original percentile
# fitted = the percentiles from the fitted lognormal
# abs_diff = fitted - target
# rel_diff_pct = percent difference realtive to target

# looks like a reasonable fit
# not reproducing the percentiles perfectly, but deviations are small enough to be accepted
# imo
```

## Checks

```{r}
beta_hat
x_ref

# calculating rr at at median for each sex
df %>%
  mutate(rr_at_median = exp(beta_hat * (med_cap - x_ref))) %>%
  dplyr::select(group, med_cap, rr_at_median)

# is beta too steep?
# rr is high
```

```{r}
# checks

dose_t1
dose_t2
dose_t3
unique(df$med_cap)
unique(df$mean_exp_dk)



```

## DALY plot

```{r}
#| eval: false
#| include: false
# need to restructure data to long format
daly_long <- results_daly_korea_simple %>%
  dplyr::select(group, YLD_med, YLL_med) %>%
  tidyr::pivot_longer(
    cols = c(YLD_med, YLL_med),
    names_to = "burden_component",
    values_to = "DALY"
  ) %>%
  dplyr::mutate(
    burden_component = dplyr::recode(
      burden_component,
      YLD_med = "YLD",
      YLL_med = "YLL"
    )
  )


# now plot can be made

daly_plot <- daly_long %>% 
  ggplot(aes(fill = burden_component, x = group, y = DALY)) +
  geom_bar(position = "stack", stat = "identity") +
  theme_classic() +
  scale_fill_brewer(palette = "PuBu") +
  labs(title = "BPS-attributable diabetes burden",
       fill = "DALY component",
       x = "Sex") +
  theme(plot.title = element_text(size = 16, face = "bold"))
  

daly_plot

# saving plot
ggsave(
  filename = "daly_plot_korea.png",
  plot = daly_plot,
  width = 7,
  height = 5,
  dpi = 300
)
```

```{r}
set.seed(123)

x_dk <- rlnorm(
  100000,
  meanlog = unique(df$meanlog_dk),
  sdlog = unique(df$sdlog_dk)
)

hist(x_dk, breaks = 100)

hist(x_dk[x_dk < 1], breaks = 100)
```

## MC TEST??

```{r}
ns <- c(1000, 3000, 5000, 10000)

mc_test_both <- crossing(
  group = df$group,
  nsim = ns
) %>%
  mutate(
    result = map2(group, nsim, function(g, n) {
      
      test_row <- df %>%
        filter(group == g) %>%
        slice(1)
      
      set.seed(123)
      
      run_mc_summary_daly_korea_simple(
        i_diabetes = test_row$i_diabetes,
        med_cap = test_row$med_cap,
        p_detectable_dk = test_row$p_detectable_dk,
        D_years = test_row$D_years,
        deaths = test_row$deaths,
        seyll = test_row$seyll,
        YLD_mode = test_row$YLD_mode,
        YLD_lower = test_row$YLD_lower,
        YLD_upper = test_row$YLD_upper,
        DW_min = DW_min,
        DW_mode = DW_mode,
        DW_max = DW_max,
        beta_hat = beta_hat,
        beta_se = beta_se,
        x_ref = x_ref,
        nsim_outer = n
      )
    })
  ) %>%
  unnest(result)
```
